### ISSUE TITLE
Fix for upcase and downcase

### ISSUE THREAD

**Issue by peeyushsingla** [vandanagarg/practice_python#3]
```
def formatArrayOfString(*args):
    formatted_strings_array = []
    for input_string in args:
        
        formatted_string = ''
        for i in range (0, len(input_string)):
            if i%2 == 0:
                formatted_char = input_string[i].lower()
            else:
                formatted_char = input_string[i].upper()
            formatted_string = formatted_string + formatted_char
        formatted_strings_array.append(formatted_string)    
      
    return formatted_strings_array
    
    
result = formatArrayOfString('peeyush', 'vandana')
print result
```

## Comments:- 

* Improve your variable/function naming every function/variable should represent what it is doing.
* Learn difference between `'peeyush', 'vandana'` and `'peeyush, vandana'`
* Your code was just handling one argument, as per our discussion we need to handle multiple args.

**Comment by vandanagarg** [comment]
Thank you Peeyush for raising this.
I have a doubt here , we are no more using the line of code (i = i+ 1) which I earlier used to increment letters in input string. What I understand is since we are using range function (#for i in range (0, len(input_string)):  ); so we need not to exclusively increment "i". 

Is my understanding correct ?

Hope I was able to explain it .

**Comment by vandanagarg** [comment]
learnt below points:

1. To improve variable/function naming - every function/variable should represent what it is doing.
2. Difference between 'peeyush', 'vandana' and 'peeyush, vandana'
3. Use of range function in for loop condition and its effect on incrementing variable value within the loop.
4. using append function to store values in an array for each o/p  and then return the array as final o/p
